stages:
  - test
  - build

test:
  stage: test
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - cd xRateTest
    - dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=../../MyProject.xml"
  artifacts:
    paths:
      - ./MyProject.xml
    reports:
      junit: ./MyProject.xml

build:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  script:
    - cd xRate
    - dotnet restore --interactive
    - dotnet build --configuration Release
    - dotnet publish --configuration Release --output ../publish/
  artifacts:
    paths:
      - ./publish/*.*
    expire_in: 1 week
  tags:
    - docker
