stages:
  - test
  - build

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - cd xRateTest
    - dotnet test --test-adapter-path:. -v d #--logger:"junit;LogFilePath=../../xRateTest.xml"
  artifacts:
    paths:
      - ./xRateTest.xml
    reports:
      junit: ./xRateTest.xml

.build_image: &build_image
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

  only:
    - main
    - prerelease
  tags:
    - docker
    - open-soft
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  <<: *build_image
  script: 
    - docker build -f Dockerfile.prod --no-cache -t registry.gitlab.com/open-soft/xrate/back:${CI_COMMIT_REF_NAME} .
    - docker push registry.gitlab.com/open-soft/xrate/back:${CI_COMMIT_REF_NAME}
